name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create .env file from GitHub Secrets
        run: |
          echo "NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_ENV_NAME=${{ secrets.NEXT_PUBLIC_ENV_NAME }}" >> .env
          echo "DB_SECRET=${{ secrets.DB_SECRET }}" >> .env

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel pull --yes --environment=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }} --token ${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }} --prod=${{ github.ref == 'refs/heads/main' }}
